# Generates the three data-driven figures for the CPM chapter from artifacts:
#   fig04_chains: water network dot file, longest chain bold, shortest chain shaded
#   fig05_service: drone destination best-route-success histogram (standalone TikZ)
#   fig06_floats: water k=32 float bounds, possibly-critical vs excluded (standalone TikZ)
# USAGE: julia -t 1 "validation/cpm_v2/make_chapter_figures.jl"

const REPO = raw"c:\Users\ohian\OneDrive - University of Strathclyde\Documents\Programmming Files\Julia Files\InformationPropagation\Info_Prop_Framework_Project"
using Pkg; Pkg.activate(REPO)
include(joinpath(REPO,"InfoPropFrmwrk","src","Algorithms","InfoPropFramework.jl")); using .InfoPropFramework
include(joinpath(REPO,"InfoPropFrmwrk","src","Algorithms","CriticalPathV2","CriticalPathV2Module.jl")); using .CriticalPathV2Module
using JSON, Printf

const FIGDIR = joinpath(REPO,"InfoPropFrmwrk","Publications","My work","CPM_Chapter_v1","figures")

# ---------- fig04: water chains ----------
# Longest-chain membership from oracle-certified runs; the shortest ROUTE is reconstructed
# by walking tight edges among the margin-zero nodes (the sorted critical list is a set,
# not a path order).
longest_chain = [3, 11, 19, 27]
wedges, wout, winc, wsrc = read_graph_to_dict(joinpath(REPO,"case studies","water","water.EDGES"))
wits, _, _ = find_iteration_sets(wedges, wout, winc)
jw = JSON.parsefile(joinpath(REPO,"case studies","water","water-cpm-inputs.json"))["time_analysis"]
d0 = Dict{Int64,Float64}(parse(Int64,kk)=>Float64(v) for (kk,v) in jw["node_durations"])
w0 = Dict{Tuple{Int64,Int64},Float64}()
for (kk,v) in jw["edge_delays"]
    m = match(r"\((\d+)\s*,\s*(\d+)\)", kk); m===nothing && continue
    w0[(parse(Int64,m[1]),parse(Int64,m[2]))] = Float64(v)
end
rs = analyze(wits, wout, winc, wsrc, d0, w0; mode=SHORTEST_PATH, atol=1e-6)
crit = Set(rs.critical)
crit_sources = sort([s for s in wsrc if s in crit])
@printf("fig04: critical sources: %s\n", string(crit_sources))
# The tied-fastest structure is a route SYSTEM: the subgraph of tight edges among the
# margin-zero stages. Every source-to-sink path through it completes at the optimum.
se = Set{Tuple{Int64,Int64}}()
for (u, c) in wedges
    if u in crit && c in crit &&
       isapprox(rs.forward[c], rs.forward[u] + get(w0,(u,c),0.0) + get(d0,c,0.0); atol=1e-6)
        push!(se, (u, c))
    end
end
covered = Set{Int64}(crit_sources)
for (u, c) in se
    push!(covered, u); push!(covered, c)
end
@assert covered == crit  # every margin-zero stage lies on the tight-edge route system
@printf("fig04: tight-edge route system: %d edges over %d stages: %s\n",
        length(se), length(crit), string(sort(collect(se))))
sset = crit
eset = Set(wedges)
lset = Set(longest_chain)
@assert isempty(intersect(lset, sset))
le = Set((longest_chain[i], longest_chain[i+1]) for i in 1:length(longest_chain)-1)
@assert issubset(le, eset)
nodes = sort(collect(union(Set(u for (u,_) in wedges), Set(v for (_,v) in wedges))))
open(joinpath(FIGDIR,"fig04_chains","fig04_chains.dot"), "w") do io
    println(io, "// Water network: longest-path chain bold double-bordered, shortest-path chain shaded.")
    println(io, "// Generated by validation/cpm_v2/make_chapter_figures.jl from oracle-certified chains.")
    println(io, "digraph chains {")
    println(io, "  rankdir=TB; nodesep=0.28; ranksep=0.5;")
    println(io, "  node [shape=circle, style=filled, fillcolor=white, fontname=\"Helvetica\", fontsize=14, penwidth=1.1, width=0.42, fixedsize=true];")
    println(io, "  edge [penwidth=1.0, arrowsize=0.7, color=gray45];")
    for n in nodes
        if n in lset
            println(io, "  $n [penwidth=2.8, peripheries=2];")
        elseif n in sset
            println(io, "  $n [fillcolor=gray85];")
        end
    end
    for (u,v) in wedges
        if (u,v) in le
            println(io, "  $u -> $v [penwidth=2.8, color=black];")
        elseif (u,v) in se
            println(io, "  $u -> $v [penwidth=2.0, color=gray20, style=dashed];")
        else
            println(io, "  $u -> $v;")
        end
    end
    println(io, "}")
end

# ---------- fig05: drone service histogram ----------
ddir = joinpath(REPO,"dag_ntwrk_files","drone-medical-delivery-network")
dnp = Dict{Int64,Float64}(parse(Int64,k)=>Float64(v)
    for (k,v) in JSON.parsefile(joinpath(ddir,"float","drone-medical-delivery-network-nodepriors.json"))["nodes"])
dlp = Dict{Tuple{Int64,Int64},Float64}()
for (k,v) in JSON.parsefile(joinpath(ddir,"float","drone-medical-delivery-network-linkprobabilities.json"))["links"]
    m = match(r"\((\d+)\s*,\s*(\d+)\)", k); m===nothing && continue
    dlp[(parse(Int64,m[1]),parse(Int64,m[2]))] = Float64(v)
end
dedges, dout, dinc, dsrc = read_graph_to_dict(joinpath(ddir,"drone-medical-delivery-network.EDGES"))
dits, _, _ = find_iteration_sets(dedges, dout, dinc)
r = analyze(dits, dout, dinc, dsrc, dnp, dlp; mode=MAX_SCALING, atol=1e-9)
sinks = [n for l in dits for n in l if isempty(get(dout,n,Set{Int64}()))]
vals = [r.forward[s] for s in sinks]
counts = [count(v -> lo <= v < lo + 0.1, vals) for lo in 0.0:0.1:0.9]
counts[end] += count(v -> v >= 1.0, vals)
println("fig05 buckets: ", counts, " total=", sum(counts))
maxc = maximum(counts)
open(joinpath(FIGDIR,"fig05_service","fig05_service.tex"), "w") do io
    println(io, "% Generated by validation/cpm_v2/make_chapter_figures.jl")
    println(io, "\\documentclass[tikz,border=6pt]{standalone}")
    println(io, "\\begin{document}")
    println(io, "\\begin{tikzpicture}[x=1.05cm, y=1mm]")
    for (i, c) in enumerate(counts)
        x0 = (i-1) * 1.0
        h = maxc == 0 ? 0.0 : 55.0 * c / maxc
        println(io, @sprintf("  \\fill[gray!55] (%.2f,0) rectangle (%.2f,%.2f);", x0+0.06, x0+0.94, h))
        println(io, @sprintf("  \\draw[gray!20!black, line width=0.4pt] (%.2f,0) rectangle (%.2f,%.2f);", x0+0.06, x0+0.94, h))
        c > 0 && println(io, @sprintf("  \\node[above, font=\\scriptsize] at (%.2f,%.2f) {%d};", x0+0.5, h, c))
    end
    println(io, "  \\draw[->, line width=0.6pt] (0,0) -- (10.35,0);")
    for i in 0:2:10
        println(io, @sprintf("  \\node[below, font=\\scriptsize] at (%.1f,0) {%.1f};", i*1.0, i/10))
    end
    println(io, "  \\draw[dashed, line width=0.8pt] (5.0,0) -- (5.0,60);")
    println(io, "  \\node[right, font=\\scriptsize] at (5.05,58) {0.5};")
    println(io, "  \\node[below=4mm, font=\\small] at (5.2,0) {best-route success};")
    println(io, "\\end{tikzpicture}")
    println(io, "\\end{document}")
end

# ---------- fig06: water k=32 float bounds ----------
rows = Tuple{Int64,Float64,Float64,Bool}[]
for line in readlines(joinpath(REPO,"validation","cpm_v2","water_k32_float_bounds.csv"))[2:end]
    p = split(line, ",")
    push!(rows, (parse(Int64,p[1]), parse(Float64,p[2]), parse(Float64,p[3]), p[5]=="true"))
end
pc = sort([t for t in rows if t[4]]; by=t->t[3])
npc = sort([t for t in rows if !t[4]]; by=t->-t[2])[1:3]
sel = vcat(pc, reverse(npc))
maxhi = maximum(t[3] for t in sel)
println("fig06: ", length(pc), " possibly-critical + 3 excluded; max float hi = ", maxhi)
open(joinpath(FIGDIR,"fig06_floats","fig06_floats.tex"), "w") do io
    println(io, "% Generated by validation/cpm_v2/make_chapter_figures.jl from water_k32_float_bounds.csv")
    println(io, "\\documentclass[tikz,border=6pt]{standalone}")
    println(io, "\\begin{document}")
    println(io, "\\begin{tikzpicture}[y=6.5mm]")
    sc = 9.0 / max(maxhi, 1e-9)
    for (i, (n, lo, hi, crit)) in enumerate(sel)
        y = i
        col = crit ? "black" : "gray!60"
        println(io, @sprintf("  \\node[left, font=\\scriptsize] at (-0.15,%d) {%d};", y, n))
        println(io, @sprintf("  \\draw[%s, line width=2.6pt] (%.3f,%d) -- (%.3f,%d);", col, lo*sc, y, hi*sc, y))
        println(io, @sprintf("  \\draw[%s, line width=0.9pt] (%.3f,%d-0.18) -- (%.3f,%d+0.18);", col, lo*sc, y, lo*sc, y))
        println(io, @sprintf("  \\draw[%s, line width=0.9pt] (%.3f,%d-0.18) -- (%.3f,%d+0.18);", col, hi*sc, y, hi*sc, y))
    end
    println(io, @sprintf("  \\draw[dashed, line width=0.7pt] (0,0.3) -- (0,%.1f);", length(sel)+0.7))
    println(io, "  \\draw[->, line width=0.6pt] (0,0.3) -- (9.4,0.3);")
    for v in 0:5:ceil(Int, maxhi)
        println(io, @sprintf("  \\node[below, font=\\scriptsize] at (%.3f,0.25) {%d};", v*sc, v))
    end
    println(io, @sprintf("  \\node[below=3.5mm, font=\\small] at (4.7,0.3) {float (time units)};"))
    println(io, "\\end{tikzpicture}")
    println(io, "\\end{document}")
end
println("figure sources written")
